In [ ]:
# Task 18: Select Dataset Columns

## Objective
Select specific rows and columns from a dataset using Pandas
loc and iloc.

## Deliverables
- Examples using loc
- Examples using iloc
- Output showing selected records
- Explanation of label-based and position-based selection

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()

# Convert it into a Pandas DataFrame
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Add readable species names
df["species"] = iris.target_names[iris.target]

print("Iris dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

display(df.head())

Iris dataset loaded successfully!
Rows: 150
Columns: 5

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [2]:
print("EXAMPLE 1: SELECT ROWS AND COLUMNS USING loc")

loc_result = df.loc[
    0:4,
    ["sepal length (cm)", "petal length (cm)", "species"]
]

display(loc_result)

EXAMPLE 1: SELECT ROWS AND COLUMNS USING loc

   sepal length (cm)  petal length (cm) species
0                5.1                1.4  setosa
1                4.9                1.4  setosa
2                4.7                1.3  setosa
3                4.6                1.5  setosa
4                5.0                1.4  setosa

In [3]:
print("EXAMPLE 2: SELECT SPECIFIC ROW LABELS")

selected_rows = df.loc[
    [0, 10, 20],
    ["sepal length (cm)", "petal length (cm)", "species"]
]

display(selected_rows)

EXAMPLE 2: SELECT SPECIFIC ROW LABELS

    sepal length (cm)  petal length (cm) species
0                 5.1                1.4  setosa
10                5.4                1.5  setosa
20                5.4                1.7  setosa

In [4]:
print("EXAMPLE 3: SELECT SETOSA RECORDS")

setosa_records = df.loc[
    df["species"] == "setosa",
    ["sepal length (cm)", "petal length (cm)", "species"]
]

display(setosa_records.head())

EXAMPLE 3: SELECT SETOSA RECORDS

   sepal length (cm)  petal length (cm) species
0                5.1                1.4  setosa
1                4.9                1.4  setosa
2                4.7                1.3  setosa
3                4.6                1.5  setosa
4                5.0                1.4  setosa

In [5]:
print("EXAMPLE 1: SELECT ROWS AND COLUMNS USING iloc")

iloc_result = df.iloc[0:5, [0, 2, 4]]

display(iloc_result)

EXAMPLE 1: SELECT ROWS AND COLUMNS USING iloc

   sepal length (cm)  petal length (cm) species
0                5.1                1.4  setosa
1                4.9                1.4  setosa
2                4.7                1.3  setosa
3                4.6                1.5  setosa
4                5.0                1.4  setosa

In [6]:
print("EXAMPLE 2: SELECT SPECIFIC ROW POSITIONS")

selected_positions = df.iloc[
    [0, 10, 20],
    [0, 2, 4]
]

display(selected_positions)

EXAMPLE 2: SELECT SPECIFIC ROW POSITIONS

    sepal length (cm)  petal length (cm) species
0                 5.1                1.4  setosa
10                5.4                1.5  setosa
20                5.4                1.7  setosa

In [7]:
print("EXAMPLE 3: SELECT A BLOCK OF DATA")

selected_block = df.iloc[5:10, 0:4]

display(selected_block)

EXAMPLE 3: SELECT A BLOCK OF DATA

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [8]:
# Select one column by its label
print("SINGLE COLUMN USING loc")
display(df.loc[:, "species"].head())

# Select multiple columns by their labels
print("MULTIPLE COLUMNS USING loc")
display(
    df.loc[
        :,
        ["sepal length (cm)", "sepal width (cm)", "species"]
    ].head()
)

# Select one column by its integer position
print("SINGLE COLUMN USING iloc")
display(df.iloc[:, 4].head())

SINGLE COLUMN USING loc

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

MULTIPLE COLUMNS USING loc

   sepal length (cm)  sepal width (cm) species
0                5.1               3.5  setosa
1                4.9               3.0  setosa
2                4.7               3.2  setosa
3                4.6               3.1  setosa
4                5.0               3.6  setosa

SINGLE COLUMN USING iloc

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

In [ ]:
## Difference Between loc and iloc

- loc selects rows and columns using labels.
- iloc selects rows and columns using integer positions.
- loc includes the ending label in a slice.
- iloc excludes the ending integer position in a slice.
- Both can select particular rows and columns together.

In [9]:
comparison = pd.DataFrame({
    "Accessor": ["loc", "iloc"],
    "Selection method": [
        "Labels",
        "Integer positions"
    ],
    "Example": [
        'df.loc[0:4, ["species"]]',
        'df.iloc[0:5, [4]]'
    ]
})

display(comparison)

  Accessor   Selection method                   Example
0      loc             Labels  df.loc[0:4, ["species"]]
1     iloc  Integer positions         df.iloc[0:5, [4]]

In [10]:
print("DATASET DIMENSIONS")
print("Shape:", df.shape)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nCOLUMN NAMES")
print(df.columns.tolist())

print("\nDATA TYPES")
print(df.dtypes)

DATASET DIMENSIONS
Shape: (150, 5)
Rows: 150
Columns: 5

COLUMN NAMES
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'species']

DATA TYPES
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
species               object
dtype: object

In [11]:
df.to_csv("iris_dataset.csv", index=False)

print("iris_dataset.csv created successfully.")

iris_dataset.csv created successfully.

In [12]:
from google.colab import files

files.download("iris_dataset.csv")